version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: mongovspostgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mongovspostgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres:
    mongodb: